### ISSUE TITLE
There is a grunt wrapper in the module but not mentioned in README

### ISSUE THREAD

**Issue by stevemao** [maxogden/dependency-check#27]
Maybe it's better to make a separate grunt module? Just to make the core minimum.

**Comment by maxogden** [comment]
+1, I am not a grunt user so I wouldn't be able to maintain it anyhow. Though I believe @voxpelli is

**Comment by voxpelli** [comment]
The grunt task is very minimal – I don' think it hurts to have it in core – but it should of course be mentioned in the README!

**Comment by stevemao** [comment]
Problem with this is users might use gulp but they are bloated with the unused grunt task. There are many examples that a module is separated into a grunt wrapper (or other wrappers) and core.

https://github.com/btford/grunt-conventional-changelog/commit/caa14d694ed14b0ec322e85533cf4e350136e501
https://github.com/stephenplusplus/grunt-wiredep
https://github.com/BrowserSync/grunt-browser-sync

I also believe the smaller the better. Usually the task wrappers are very small

https://github.com/ben-eb/gulp-svgmin/blob/master/index.js

**Comment by stevemao** [comment]
Also because of the naming, https://github.com/sindresorhus/load-grunt-tasks can't auto load this "grunt task"

**Comment by voxpelli** [comment]
Updated the README now to contain [grunt usage](https://github.com/maxogden/dependency-check#grunt-usage) instructions as well as to fully reference all available [cli options](https://github.com/maxogden/dependency-check#cli-usage).

The Grunt task is pretty much a minimal 49-line 1:1 mapping to the available CLI-options. I think this module still only does one thing, but it provides three interfaces for that one thing – CLI, Node module and Grunt task.

While `load-grunt-tasks` is handy, users can still load this module in the traditional way of `grunt.loadNpmTasks('dependency-check')`.

**Comment by stevemao** [comment]
I guess you could add a gulp task here. It won't be too many lines.

**Comment by stevemao** [comment]
BTW if I search on http://gruntjs.com/plugins, is this plugin visible?

**Comment by sindresorhus** [comment]
I think the grunt task should be a separate module. LOCs is a bad measure of what should be a separate module. For reference, here's my smallest [module](https://github.com/sindresorhus/max-safe-integer/blob/master/index.js) and [grunt task](https://github.com/sindresorhus/grunt-electron/blob/master/tasks/electron.js) :p

Most users aren't interested in the grunt task, and having it in the package and readme just causes bloat and noise.

I've made a separate grunt task for this module: https://github.com/sindresorhus/grunt-dependency-check

-

As for gulp, the recommended gulp way is to just use the vanilla node module. No wrapper needed.

**Comment by voxpelli** [comment]
@sindresorhus I’m not saying LOCs should be the measure, I’m well aware of small modules and I have [some](https://github.com/bloglovin/node-bunyan-duckling) myself :wink: 

But as I see it:

If something like this task either adds new logic or a substantial amount of code – then it should be a separate module to avoid bloat and noise and keep the module focused.

If it does neither though, but just simply maps the existing interface to  new one, then it can just as well be part of the original module as be a new one – I see neither as better than the other – I think both works and neither are very bloated or noisy.

I submitted this task as a PR, #3, as I felt more projects than [lintlovin](https://github.com/bloglovin/lintlovin) could have a use of it and felt that it would be better of maintained in sync with the upstream project rather than as a small side-project by me.

Anyhow – I won’t stay in the way of having this as a separate module if that’s where the general preference is – but will leave it to @maxogden to decide whether he wants it removed or not.

@stevemao No, it does not currently show up there – actually wasn't aware of that page, must have done all of my grunt-task searching directly on npm. Seems like a new keyword would be needed for this module to show there

**Comment by sindresorhus** [comment]
Yeah, it's probably subjective, but including everything in the main module is also a slippery slope. What about Broccoli? Or the next build tools? The beauty of the node ecosystem is small focused modules. I feel it loses that by bundling task runner plugins. There's also issues like discovery. The `grunt-` prefix in the name makes it pretty clear.

> I submitted this task as a PR, #3, as I felt more projects than lintlovin could have a use of it and felt that it would be better of maintained in sync with the upstream project rather than as a small side-project by me.

From experience it's usually the opposite effect. By being separate the author of the main module, which in this case don't even use grunt, don't have to care about the plugin and issues around it.

-

I'd be happy to transfer the repo if anyone wants it, but I can easily maintain it too, no problem.

**Comment by stevemao** [comment]
Would it be better if we keep this one just the core and create a `dependency-check-cli`?

**Comment by maxogden** [comment]
ironically the amount of time spent bikeshedding in this thread has now surpassed the amount of time required to maintain the grunt module, so I'm closing this now :)
