### ISSUE TITLE
usage with gulp.js "no entry paths found"

### ISSUE THREAD

**Issue by ORESoftware** [maxogden/dependency-check#35]
can I use this lib with gulp.js or mocha?

**Comment by ORESoftware** [comment]
also, I get this "error"

```
CACSVML-13295:smartconnect amills001c$ ***dependency-check ./package.json ***
No entry paths found
CACSVML-13295:smartconnect amills001c$ ls -a
.                       .git                    app.js                  config                  helpers                 node_modules            sample_data             test+
..                      .gitignore              artifacts               cs_query_terms          ivrbucket_data          package.json            scripts                 testx
.DS_Store               .idea                   aux                     enriched_data           json_response_templates public                  server                  views
.eslintignore           .jshintrc               bin                     events                  lib                     redisConnections        setup
.eslintrc               README.md               caches                  heartbeatData           my_old_code             routes                  test
CACSVML-13295:smartconnect amills001c$ sudo chmod -R 777 .
CACSVML-13295:smartconnect amills001c$ dependency-check ./package.json 
No entry paths found
```

**Comment by piotrd** [comment]
Any update on this one? I'm getting `"No entry paths found"` as well.

**Comment by maxogden** [comment]
This module should work with any code that uses node's `require` function. You also need to specify your initial entry file somehow. By default it uses `main` from package.json but you can specify another root entry with the `--entry` flag

**Comment by voxpelli** [comment]
In addition to what Max has already pointed out and in regards to the very first question:

You can use this module either through it's command line interface and then eg. running it before or after you run your gulp or mocha script, like: `dependency-check && mocha`, or you can run it programmatically by including it as a node module within gulp and doing whatever you want with it in there.

As there has been no additional feedback to this support question since Max response, I will close this for now.
