### ISSUE TITLE
support hapi manifest

### ISSUE THREAD

**Issue by travi** [maxogden/dependency-check#68]
when using [glue](https://github.com/hapijs/glue) to build a hapi server manifest, dependencies defined in the manifest are not found and are reported as unused.

an example manifest file can be found [here](https://github.com/travi/travi.org-admin/blob/master/src/server/manifest.js)

**Comment by blakeembrey** [comment]
Having not really used `glue` or `hapi`, is the issue that the thing you believe to be requires not being picked up because they are indirectly required? I don't think this is the right place to enable that use-case, you could make a custom detective: https://github.com/maxogden/dependency-check#--detective.

**Comment by blakeembrey** [comment]
Closing since there's been no response and it seems custom detective is still the best approach.
